logging.level:
  org.springframework.boot.autoconfigure: INFO
server:
  port: 3000

spring:
  jmx:
    enabled: false

sajari:
  key-id: ${key.id}
  key-secret: ${key.secret}
  collection-id: ${collection.id}
  api-url: https://api-gateway.sajari.com

customer:
  google-product-feed-url: ${google.product.feed.url}
